データサイエンス特論授業課題第2回
作成日: 2022年6月25日
作成者: M1 203324 紺谷優志

IRISのデータに対し、平均と共分散行列を求め、ランダムに選んだ2つのデータのユークリッド距離とマハラノビス距離を求める。

In [53]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random
from scipy.spatial.distance import cdist 
from sklearn.datasets import load_iris  # irisデータセットをロード

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names) #irisデータをpandasに変換

In [46]:
# ラベル名を別のDataFrameで管理
label=pd.Series(data=iris.target_names[iris.target])
label

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Length: 150, dtype: object

In [181]:
# 平均となる４次元ベクトル
mu = np.zeros(len(df.columns.values))
for i, col in enumerate(df.columns.values):
    mu[i]=df[col].mean()
print("平均値={0}".format(mu))

平均値=[5.84333333 3.05733333 3.758      1.19933333]


In [182]:
# 共分散行列
cov=df.cov()
cov

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [240]:
# 0~149の間で乱数を2つ生成
#x_num=random.randint(0,df.index.stop-1)
#y_num=random.randint(0,df.index.stop-1)
x_num=115
y_num=16

#x=df.loc[x_num]
#y=df.loc[y_num]
x=df[x_num:x_num+1]
y=df[y_num:y_num+1]
s=pd.concat([x,y]).cov()
#s=pd.merge(x,y)
print("1つ目のデータ:index = {0}, {1}:{2}".format(x_num,label[x_num],x.values))
print("2つ目のデータ:index = {0}, {1}:{2}".format(y_num,label[y_num],y.values))

'''
x=np.array(x)
y=np.array(y)
s=np.array(s)
np.linalg.norm(x-y)
(x-y).T,(x-y)

np.dot((x-y).T,s)
'''
#np.dot((x-y),s)
x=np.array(x).T
y=np.array(y).T
sa=np.array(s).T
sb=np.linalg.inv(s)

"""aa=np.dot((x-y).T,s)
bb=np.dot(aa,(x-y))
cc=np.sqrt(bb[0][0])
np.linalg.norm(x-y),aa,bb,cc"""
print(x,y,sa)
print((x-y).T)
aa=np.dot((x-y).T,sb)
np.dot(aa,(x-y))
(x-y).T @ sb @ (x-y)

1つ目のデータ:index = 115, virginica:[[6.4 3.2 5.3 2.3]]
2つ目のデータ:index = 16, setosa:[[5.4 3.9 1.3 0.4]]
[[6.4]
 [3.2]
 [5.3]
 [2.3]] [[5.4]
 [3.9]
 [1.3]
 [0.4]] [[ 0.5   -0.35   2.     0.95 ]
 [-0.35   0.245 -1.4   -0.665]
 [ 2.    -1.4    8.     3.8  ]
 [ 0.95  -0.665  3.8    1.805]]
[[ 1.  -0.7  4.   1.9]]


array([[-0.88]])